### PR TITLE
Add adamsbridge RDL and HMAC hardware peripheral fix

### PR DESCRIPTION
**Pull request by ArthurHeymans**

### CODE REVIEW

**Comment by ArthurHeymans** [comment]
TODO 'external mem' inside RDL needs to be translated into a register array.

**Comment by ArthurHeymans** [comment]
The order of RDL files included does matter and the adamsbridge needs to be before caliptra_reg.rdl and after soc_ifc_reg.rdl...

**Comment by ArthurHeymans** [comment]
These external mem blocks are actually register arrays in mldsa. However this unblocks https://github.com/chipsalliance/caliptra-sw/pull/1747

**Review by swenson — APPROVED** [review]
LGTM

**Review by mhatrevi — DISMISSED** [review]

**Review by mhatrevi — APPROVED** [review]

**Pull request merged**
