### PR TITLE
Pass fpga_realtime feature from runtime crate to hw-model

### PR DESCRIPTION
**Pull request by jlmahowa-amd**

### CODE REVIEW

**Review by jhand2 — APPROVED** [review]

**Comment by jhand2** [comment]
Huh. CI failure looks like a flaky infra issue. Trying again.

```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3475 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Comment by korran** [comment]
> Huh. CI failure looks like a flaky infra issue. Trying again.
> 
> ```
> E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3475 (apt-get)
> E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> ```

Which workflow was that? Do you have a link?

**Comment by korran** [comment]
> > Huh. CI failure looks like a flaky infra issue. Trying again.
> > ```
> > E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3475 (apt-get)
> > E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> > ```
> 
> Which workflow was that? Do you have a link?

https://github.com/chipsalliance/caliptra-sw/actions/runs/7805756017/job/21290640248?pr=1317

**Comment by jhand2** [comment]
> > > Huh. CI failure looks like a flaky infra issue. Trying again.
> > > ```
> > > E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3475 (apt-get)
> > > E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> > > ```
> > 
> > 
> > Which workflow was that? Do you have a link?
> 
> https://github.com/chipsalliance/caliptra-sw/actions/runs/7805756017/job/21290640248?pr=1317
> 
> Hmm, these Ubuntu GCE images must update themselves in the background...

Ok, now the CI failure is test timeouts. I wonder if that's still because of flakiness related to sleep states in RT, or actually caused by this PR.

**Comment by korran** [comment]
> > > > Huh. CI failure looks like a flaky infra issue. Trying again.
> > > > ```
> > > > E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 3475 (apt-get)
> > > > E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
> > > > ```
> > > 
> > > 
> > > Which workflow was that? Do you have a link?
> > 
> > 
> > https://github.com/chipsalliance/caliptra-sw/actions/runs/7805756017/job/21290640248?pr=1317
> > Hmm, these Ubuntu GCE images must update themselves in the background...
> 
> Ok, now the CI failure is test timeouts. I wonder if that's still because of flakiness related to sleep states in RT, or actually caused by this PR.

It appears to be the WFI issue. Probably need to merge from main.

The ubuntu issue should be resolved by https://github.com/chipsalliance/caliptra-sw/pull/1321

**Pull request closed without merging**
