### PR TITLE
Remove cfg 1.0

### PR DESCRIPTION
**Pull request by ArthurHeymans**
The 1.0 hardware is not supported in the 2.x branch.
When stabilizing 2.0 some similar code might need to be added back to support 2.0 ROM with later runtime revisions.

### CODE REVIEW

**Review by mhatrevi — APPROVED** [review]

**Review by swenson — APPROVED** [review]
LGTM

**Comment by ArthurHeymans** [comment]
It looks like a required flow is set up for check_policy

**Comment by ArthurHeymans** [comment]
I added the policy back with a NOOP to pass CI to be unblocked.

**Review by mhatrevi — APPROVED** [review]

**Review by swenson — APPROVED** [review]
LGTM

**Comment by ArthurHeymans** [comment]
Since verilator and FPGA aren't going to work from the start, can we merge?

**Review by swenson — APPROVED** [review]
LGTM

**Review by jhand2 — APPROVED** [review]

**Pull request merged**
