### PR TITLE
Remove dead FHT code.

### PR DESCRIPTION
**Pull request by bluegate010**

### CODE REVIEW

**Comment by bluegate010** [comment]
Alternatively, we can invoke `print_fht()` [here](https://github.com/chipsalliance/caliptra-sw/blob/6248d3fbf24a53ee95890ca98ffb1c2dd567e6fc/fmc/src/hand_off.rs#L73).

**Review by FerralCoder — APPROVED** [review]

**Comment by jhand2** [comment]
> Alternatively, we can invoke `print_fht()` [here](https://github.com/chipsalliance/caliptra-sw/blob/6248d3fbf24a53ee95890ca98ffb1c2dd567e6fc/fmc/src/hand_off.rs#L73).

This seems valuable for debugging

**Comment by korran** [comment]
> > Alternatively, we can invoke `print_fht()` [here](https://github.com/chipsalliance/caliptra-sw/blob/6248d3fbf24a53ee95890ca98ffb1c2dd567e6fc/fmc/src/hand_off.rs#L73).
> 
> This seems valuable for debugging

Yeah, can we keep that print_fht() function around (add the `#[allow(dead_code)]` attribute on it if necessary)?

**Comment by bluegate010** [comment]
Have amended this PR to leave `print_fht()` in place. To invoke it from FMC will require that we increase FMC's size from 16 to 17k.

**Review by rusty1968 — APPROVED** [review]

**Review by mhatrevi — APPROVED** [review]

**Pull request merged**
