### PR TITLE
Make test-fmc use FIRMWARE_LOAD to trigger the update reset.

### PR DESCRIPTION
**Pull request by korran**
This is necessary to work around the race condition in #786.

### CODE REVIEW

**Comment by bluegate010** [comment]
Will probably also want to make the same change [here](https://github.com/chipsalliance/caliptra-sw/blob/b1f43f36f8a5e2d262b04c702b324baf8addd33c/fmc/tests/test_rtalias.rs#L179).

**Comment by korran** [comment]
(Waiting for verilator tests to run to confirm that this fully fixes #786)

**Comment by korran** [comment]
Confirmed that the tests passed under verilator.

**Review by fdamato — APPROVED** [review]
Approved for the HW Model Changes

**Pull request merged**
