### PR TITLE
Add libcaliptra (SOC C Integration API Library) into hw release archieve

### PR DESCRIPTION
**Pull request by fdamato**

### CODE REVIEW

**Comment by wmaroneAMD** [comment]
Do we expect the libcaliptra examples to build from within the release directory?

**Comment by fdamato** [comment]
> Do we expect the libcaliptra examples to build from within the release directory?

Not necessarily

**Comment by wmaroneAMD** [comment]
Then we may want to exclude the libcaliptra/examples/ subdirectory from the release as it doesn't have required inputs to do so.

**Comment by fdamato** [comment]
I don`t think it is necessary...It will only create complexity IMHO

**Review by wmaroneAMD — APPROVED** [review]

**Review by attzonko — APPROVED** [review]

**Review by jlmahowa-amd — APPROVED** [review]

**Pull request merged**
