### PR TITLE
sw-emulator: Add physical memory protection (PMP)

### PR DESCRIPTION
**Pull request by swenson**
This will allow us to be able to move some values out of the data vault and into DCCM, which we can lock for access as appropriate.

Originally written by @Elizafox for the 2.0 MCU emulator.

### CODE REVIEW

**Comment by swenson** [comment]
Based on @jhand2's comments, I'll put this behind a feature flag.

**Comment by jhand2** [comment]
Do you have a link to a hw spec for how VeeR PMP works? Would be helpful for reviewing this.

**Comment by swenson** [comment]
https://riscv.org/blog/2024/03/adding-physical-memory-protection-to-the-veer-el2-risc-v-core-2/ describes it in overview, but the privileged spec for RISC-V contains most of the details.

**Comment by swenson** [comment]
Closing this in favor of a PR to `main-2.x`

**Pull request closed without merging**
