### PR TITLE
Adding LMS KAT to RT boot

### PR DESCRIPTION
**Pull request by nquarton**

### CODE REVIEW

**Comment by nquarton** [comment]
This is the non-ideal approach of always running the LMS KAT at the start of RT FW (before processing commands). Ideally, this would be run exactly once as/if needed before an LMS operation is performed in runtime. This gets a little tricky in rust though as it requires static state to be shared about whether or not the KAT has been run.

**Comment by sree-revoori1** [comment]
Can we add a bool to the drivers struct indicating whether or not the KAT has been run instead?

**Comment by nquarton** [comment]
> Can we add a bool to the drivers struct indicating whether or not the KAT has been run instead?

I did consider that. It's an accessible place to put some state. The only issue is the drivers don't bring in KATs as a crate. So either
1. The runtime code needs to enforce this rule, check/update the state, and run the KAT. Certainly possible but feels a little disaggregated.
2. The drivers need to have a circular dependency on the KATs (is this okay/allowed?)

But if people still like this path (or I'm missing a better option) then I can absolutely do this.

**Comment by nquarton** [comment]
I have updated this implementation to store state in the LMS driver.

**Review by jhand2 — APPROVED** [review]

**Review by mhatrevi — DISMISSED** [review]

**Review by jhand2 — APPROVED** [review]

**Review by mhatrevi — APPROVED** [review]

**Pull request merged**
