### PR TITLE
Enable FPGA Clock Gating

### PR DESCRIPTION
**Pull request by jlmahowa-amd**

### CODE REVIEW

**Comment by korran** [comment]
To get the policy check to pass you'll have to rebase or merge from main.

**Review by korran — APPROVED** [review]

**Review by korran — CHANGES_REQUESTED** [review]
Luke tells me this is not ready to merge yet

**Comment by jlmahowa-amd** [comment]
Last trouble is that the clock gate conversion only works when building using the GUI. Should be close.

**Comment by jlmahowa-amd** [comment]
Vivado took me for a ride, and the patch was fine as is. I did make a small optimization to only run the clock gate conversion pass when we have it enabled.

**Review by korran — APPROVED** [review]

**Pull request merged**
