### PR TITLE
Remove unnecessary image arg from trait functions.

### PR DESCRIPTION
**Pull request by bluegate010**

### CODE REVIEW

**Review by mhatrevi — CHANGES_REQUESTED** [review]
We need additional metadata from the Image object (e.g.: image size), so we need that Trait.

**Comment by bluegate010** [comment]
@mhatrevi is that a future enhancement? Currently it looks like the image verification routines just use the TOC to find the FMC and FW size.

**Comment by mhatrevi** [comment]
> @mhatrevi is that a future enhancement? Currently it looks like the image verification routines just use the TOC to find the FMC and FW size.

Yes, there are couple of TODO checks in verifier.rs regarding this.

**Comment by bluegate010** [comment]
Ah, understood.

**Pull request closed without merging**
