### PR TITLE
DPE: Use DPE as a dependency crate

### PR DESCRIPTION
**Pull request by ArthurHeymans**
Rather use DPE as a crate dependency than a git submodule, as it makes it easier to handle.

### CODE REVIEW

**Comment by ArthurHeymans** [comment]
DPE contains both go and rust code, which CI both use. Maybe it's possible to parse the cargo lock file and update the go deps for CI, but then a submodule might be easier after all.

**Comment by ArthurHeymans** [comment]
> DPE contains both go and rust code, which CI both use. Maybe it's possible to parse the cargo lock file and update the go deps for CI, but then a submodule might be easier after all.

Cargo can print out the used DPE version which in turn can be used for the golang dep.

**Review by jhand2 — CHANGES_REQUESTED** [review]
@ArthurHeymans The issue is that there's still a fair bit of churn, so there are likely to be changes in that repo that will break the build here. Using a submodule allows us target a specific commit so we can wait to update the submodule in a PR that also fixes up any of the API calls from caliptra-sw

**Comment by ArthurHeymans** [comment]
> @ArthurHeymans The issue is that there's still a fair bit of churn, so there are likely to be changes in that repo that will break the build here. Using a submodule allows us target a specific commit so we can wait to update the submodule in a PR that also fixes up any of the API calls from caliptra-sw

Cargo also features this "cargo update -p dpe --precise <commit hash>" and the Cargo.lock file should use only a specific commit.

**Comment by jhand2** [comment]
> > @ArthurHeymans The issue is that there's still a fair bit of churn, so there are likely to be changes in that repo that will break the build here. Using a submodule allows us target a specific commit so we can wait to update the submodule in a PR that also fixes up any of the API calls from caliptra-sw
> 
> Cargo also features this "cargo update -p dpe --precise " and the Cargo.lock file should use only a specific commit.

We also need to keep the golang dependency in sync with the rust dependency. This seems more complicated than just using a submodule.

Is there a specific thing you're trying to do that is difficult with a submodule?

**Comment by ArthurHeymans** [comment]
> > > @ArthurHeymans The issue is that there's still a fair bit of churn, so there are likely to be changes in that repo that will break the build here. Using a submodule allows us target a specific commit so we can wait to update the submodule in a PR that also fixes up any of the API calls from caliptra-sw
> > 
> > 
> > Cargo also features this "cargo update -p dpe --precise " and the Cargo.lock file should use only a specific commit.
> 
> We also need to keep the golang dependency in sync with the rust dependency. This seems more complicated than just using a submodule.
> 
> Is there a specific thing you're trying to do that is difficult with a submodule?

Not really but I just often forget to do update submodule.

**Comment by ArthurHeymans** [comment]
Probably not worth it as both rust and go programs depend on the submodule

**Pull request closed without merging**
